# Generated by Django 3.2.8 on 2021-11-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Order', '0002_order_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default='0'),
        ),
    ]
