# Generated by Django 3.2.8 on 2021-11-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20211122_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_description',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
    ]
